/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wisnu
 */
public class Edit_PenjAdmin extends javax.swing.JFrame {
private Connection con = KoneksiDatabase.getkoneksi();
private DefaultTableModel tabmode;
private String tgl;
    
    /**
     * Creates new form Edit_PenjAdmin
     */
    public Edit_PenjAdmin() {
        initComponents();
        
    }

 private void aktif(){
        notrans.setEnabled(true);
        nama_sepatu.setEnabled(true);
        warna.setEnabled(true);
        harga.setEnabled(true);
        jumlah_beli.setEnabled(true);
        sub_total.setEnabled(true);
        total.setEnabled(true);
        bayar.setEnabled(true);
        kembalian.setEnabled(true);
        notrans.requestFocus();
    }   
 private void kosongkan()
{ 
notrans.setText(""); 
nama_sepatu.setText("");
warna.setText("");
harga.setText("");
jumlah_beli.setText("");
sub_total.setText("");
total.setText("");
bayar.setText("");
kembalian.setText("");
notrans.requestFocus();
 }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nama_sepatu = new javax.swing.JTextField();
        warna = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        sub_total = new javax.swing.JTextField();
        jumlah_beli = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cari_kode_transaksi = new javax.swing.JTextField();
        cari_nomor_transaksi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        notrans = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 14, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Edit Transaksi Penjualan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 11, -1, -1));

        jLabel3.setText("Nama Sepatu");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 103, -1, -1));

        jLabel4.setText("Warna");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 138, -1, -1));

        jLabel5.setText("Harga");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 173, -1, -1));

        jLabel6.setText("Jumlah Beli");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 211, -1, -1));

        jLabel7.setText("Sub Total");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 249, -1, -1));

        jLabel8.setText("Total");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 103, -1, -1));

        jLabel9.setText("Bayar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 138, -1, -1));

        jLabel10.setText("Kembalian");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, -1, -1));

        nama_sepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_sepatuActionPerformed(evt);
            }
        });
        getContentPane().add(nama_sepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 100, 150, -1));
        getContentPane().add(warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 132, 150, -1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 170, 150, -1));
        getContentPane().add(sub_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 246, 150, -1));
        getContentPane().add(jumlah_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 208, 150, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 150, -1));
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 150, -1));
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 150, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Cari No Transaksi");

        cari_kode_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_kode_transaksiActionPerformed(evt);
            }
        });

        cari_nomor_transaksi.setText("cari");
        cari_nomor_transaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_nomor_transaksiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cari_nomor_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cari_kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(cari_kode_transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cari_nomor_transaksi)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 150, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/Edit.png"))); // NOI18N
        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 90, 40));

        jLabel2.setText("No Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(notrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 150, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/cancel.png"))); // NOI18N
        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 100, 40));

        setSize(new java.awt.Dimension(633, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Transaksi_Penjualan_Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "Update transpenjualan set no_transaksi=?, nama_sepatu=?,warna=?,harga=?,jumlah_beli=?,"
                + "sub_total=?,total=?,bayar=?,kembalian=? where no_transaksi=?";
            PreparedStatement stat = con.prepareStatement (sql);  
            stat.setString(1, notrans.getText());
            stat.setString(2, nama_sepatu.getText());
            stat.setString(3, warna.getText());
            stat.setString(4, harga.getText());
            stat.setString(5, jumlah_beli.getText());
            stat.setString(6, sub_total.getText());
            stat.setString(7, total.getText());
            stat.setString(8, bayar.getText());
            stat.setString(9, kembalian.getText());
            stat.setString(10, cari_kode_transaksi.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
            notrans.requestFocus();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" + e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cari_nomor_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_nomor_transaksiActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Nomor Transaksi","Nama Sepatu","Warna","Harga","Jumlah Beli","Sub Total","Total","Bayar","Kembalian"};
        tabmode = new DefaultTableModel(null, Baris);
        String sql = "select * from transpenjualan where no_transaksi like '%"+ cari_kode_transaksi.getText()+"%'";
        try{
            java.sql.Statement stat = con.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("no_transaksi");
                String b= hasil.getString("nama_sepatu");
                String c = hasil.getString("warna");
                String d = hasil.getString("harga");
                String e = hasil.getString("jumlah_beli");
                String f = hasil.getString("sub_total");
                String g = hasil.getString("total");
                String h = hasil.getString("bayar");
                String i = hasil.getString("kembalian");
                
                
                String[] data ={a,b,c,d,e,f,g,h,i};
                tabmode.addRow(data);
                notrans.setText(a);
                nama_sepatu.setText(b);
                warna.setText(c);
                harga.setText(d);
                jumlah_beli.setText(e);
                sub_total.setText(f);
                total.setText(g);
                bayar.setText(h);
                kembalian.setText(i);
                
            }
        } catch (SQLException e) { 
            
    }
    }//GEN-LAST:event_cari_nomor_transaksiActionPerformed

    private void cari_kode_transaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_kode_transaksiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_kode_transaksiActionPerformed

    private void nama_sepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_sepatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_sepatuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from transpenjualan where no_transaksi='"+cari_kode_transaksi.getText()+"'";
            try{
                PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil diHapus");
                kosongkan();
                cari_kode_transaksi.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal di Hapus" +e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit_PenjAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit_PenjAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit_PenjAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit_PenjAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit_PenjAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField cari_kode_transaksi;
    private javax.swing.JButton cari_nomor_transaksi;
    private javax.swing.JTextField harga;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jumlah_beli;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField nama_sepatu;
    private javax.swing.JTextField notrans;
    private javax.swing.JTextField sub_total;
    private javax.swing.JTextField total;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
