/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan;

import com.mysql.jdbc.Statement;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wisnu
 */
public class Input_Supplier extends javax.swing.JFrame {
private Connection con = new KoneksiDatabase().getkoneksi();
private DefaultTableModel tabmode;
private Statement stat;
private ResultSet res;
private String t;

protected void aktif (){
    kode_supplier.setEnabled(true);
    nama_supplier.setEnabled(true);
    alamat.setEnabled(true);
    email.setEnabled(true);
    no_telp.setEnabled(true);
    kodebarang.setEnabled(true);
    namabarang.setEnabled(true);
    hargasatuan.setEnabled(true);
    kode_supplier.requestFocus();
}

private void kosongkan()
{ 
kode_supplier.setText(""); 
nama_supplier.setText("");
alamat.setText("");
email.setText("");
no_telp.setText("");
kodebarang.setText("");
namabarang.setText("");
hargasatuan.setText("");
kode_supplier.requestFocus();
 } 

private void datatable(){
        Object[] Baris = {"Kode Supplier","Nama Supplier","Alamat","Email","No Telp","Kode Barang","Nama Barang","Harga Satuan"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_supplier.setModel(tabmode);
        String sql = "select * from supplier";
        try{
            java.sql.Statement stat = con.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("Kode_Supplier");
                String b = hasil.getString("Nama_Supplier");
                String c = hasil.getString("Alamat");
                String d = hasil.getString("Email");
                String e = hasil.getString("No_Telp");
                String f = hasil.getString("kodebarang");
                String g = hasil.getString("namabarang");
                String h = hasil.getString("hargasatuan");
                
                String[] data ={a,b,c,d,e,f,g,h};
                tabmode.addRow(data);
            }
        } catch (SQLException e) { 
            
    }
    }
    /**
     * Creates new form Input_Supplier
     */
    public Input_Supplier() {
        initComponents();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kode_supplier = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        nama_supplier = new javax.swing.JTextField();
        no_telp = new javax.swing.JTextField();
        btn_tmbh = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cari_kode_supplier = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_supplier = new javax.swing.JTable();
        email = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        alamat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kodebarang = new javax.swing.JTextField();
        namabarang = new javax.swing.JTextField();
        hargasatuan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("INPUT SUPPLIER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel2.setText("Kode Supplier");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, -1, 20));

        jLabel3.setText("Nama Supplier");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 20));

        jLabel5.setText("Email");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/home-run.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));
        jPanel1.add(kode_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 50, 100, -1));

        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/Zoom.png"))); // NOI18N
        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 80, -1));
        jPanel1.add(nama_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 83, 200, -1));
        jPanel1.add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, -1));

        btn_tmbh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/input.png"))); // NOI18N
        btn_tmbh.setText("Tambah");
        btn_tmbh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tmbhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tmbh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, 40));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 100, 40));

        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/Delete.png"))); // NOI18N
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 330, 100, 40));

        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/Edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 100, 40));

        jLabel6.setText("Cari Kode Supplier");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));
        jPanel1.add(cari_kode_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 100, -1));

        tabel_supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tabel_supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_supplierMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_supplier);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 570, 170));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        jLabel8.setText("No.Telp");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 206, -1, -1));
        jPanel1.add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 200, -1));

        jLabel9.setText("Kode Barang");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel10.setText("Nama Barang");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel11.setText("Harga Satuan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        jPanel1.add(kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 200, -1));
        jPanel1.add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 200, -1));
        jPanel1.add(hargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1002, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(997, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        Object[] Baris = {"Kode_Supplier","Nama_Supplier","Alamat","Email","No_Telp","Kode Barang","Nama Barang","Harga Satuan"};
        DefaultTableModel tabmode = new DefaultTableModel(null, Baris);
        tabel_supplier.setModel(tabmode);
        String sql = "select * from supplier where Kode_Supplier like '%"+ cari_kode_supplier.getText()+"%'";
        try{
            java.sql.Statement stat = con.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("Kode_Supplier");
                String b = hasil.getString("Nama_Supplier");
                String c = hasil.getString("Alamat");
                String d = hasil.getString("Email");
                String e = hasil.getString("No_Telp");
                String f = hasil.getString("kodebarang");
                String g = hasil.getString("namabarang");
                String h = hasil.getString("hargasatuan");

                String[] data ={a,b,c,d,e,f,g,h};
                tabmode.addRow(data);
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_tmbhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tmbhActionPerformed
        // TODO add your handling code here:
        String sql = "insert into supplier values(?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = con.prepareStatement(sql);
            stat.setString(1, kode_supplier.getText());
            stat.setString(2, nama_supplier.getText());
            stat.setString(3, alamat.getText());
            stat.setString(4, email.getText());
            stat.setString(5, no_telp.getText());
            stat.setString(6, kodebarang.getText());
            stat.setString(7, namabarang.getText());
            stat.setString(8, hargasatuan.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            kosongkan();
            kode_supplier.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan" +e);
        }
    }//GEN-LAST:event_btn_tmbhActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from supplier where kode_supplier='"+kode_supplier.getText()+"'";
            try{
                PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil diHapus");
                kosongkan();
                kode_supplier.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal di Hapus" +e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Update supplier set Nama_Supplier=?,Alamat=?,Email=?,No_Telp=?,kodebarang=?,namabarang=?,hargasatuan=? where Kode_Supplier=?";
            PreparedStatement stat = con.prepareStatement (sql);
            stat.setString(1, nama_supplier.getText());
            stat.setString(2, alamat.getText());
            stat.setString(3, email.getText());
            stat.setString(4, no_telp.getText());
            stat.setString(5, kodebarang.getText());
            stat.setString(6, namabarang.getText());
            stat.setString(7, hargasatuan.getText());
            stat.setString(8, kode_supplier.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
            kosongkan();
            kode_supplier.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" +e);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tabel_supplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_supplierMouseClicked
        // TODO add your handling code here:
        int bar = tabel_supplier.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();

        kode_supplier.setText(a);
        nama_supplier.setText(b);
        alamat.setText(c);
        email.setText(d);
        no_telp.setText(e);
        kodebarang.setText(f);
        namabarang.setText(g);
        hargasatuan.setText(h);
        
    }//GEN-LAST:event_tabel_supplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_tmbh;
    private javax.swing.JTextField cari_kode_supplier;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hargasatuan;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kode_supplier;
    private javax.swing.JTextField kodebarang;
    private javax.swing.JTextField nama_supplier;
    private javax.swing.JTextField namabarang;
    private javax.swing.JTextField no_telp;
    private javax.swing.JTable tabel_supplier;
    // End of variables declaration//GEN-END:variables
}
