/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author wisnu
 */
public class Transaksi_Penjualan_Kasir extends javax.swing.JFrame {
private Connection con = KoneksiDatabase.getkoneksi();
private DefaultTableModel tabmode;
private String tgl;
    
    public Transaksi_Penjualan_Kasir() {
        initComponents();
        datatable();
        
    }

    private void datatable(){
        Object[] Baris = {"No Transaksi", "Tanggal","Nama Sepatu","Warna","Harga","Jumlah Beli","Sub Total","Total","Bayar","Kembalian"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_transaksi.setModel(tabmode);
        String sql1 = "SELECT * FROM `transpenjualan`";
        try{
            java.sql.Statement stat = con.createStatement();
            ResultSet hasil = stat.executeQuery(sql1);
            while(hasil.next()){
                String a = hasil.getString("no_transaksi");
                String b = hasil.getString("tanggal");
                String c = hasil.getString("nama_sepatu");
                String d = hasil.getString("warna");
                String e = hasil.getString("harga");
                String f = hasil.getString("jumlah_beli");
                String g = hasil.getString("sub_total");
                String h = hasil.getString("total");
                String i = hasil.getString("bayar");
                String j = hasil.getString("kembalian");
                
                
                String[] data ={a,b,c,d,e,f,g,h,i,j};
                tabmode.addRow(data);
            }
            
            
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
    }
    }

private void aktif(){
        
        no_trans.setEnabled(true);
        kode_sepatu.setEnabled(true);
        nama_sepatu.setEnabled(true);
        warna.setEnabled(true);
        harga.setEnabled(true);
        kode_sepatu.requestFocus();
    }

private void kosongkan()
{
        tanggal.setDateFormatString("");
        no_trans.setText("");
        kode_sepatu.setText(""); 
        nama_sepatu.setText("");
        warna.setText("");
        harga.setText("");
        kode_sepatu.requestFocus();
 } 



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no_trans = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kode_sepatu = new javax.swing.JTextField();
        nama_sepatu = new javax.swing.JTextField();
        warna = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        cari_sepatu = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jumlah_beli = new javax.swing.JTextField();
        sub_total = new javax.swing.JTextField();
        tambah = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("No Transaksi");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        jLabel4.setText("Tanggal");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        no_trans.setEnabled(false);
        getContentPane().add(no_trans, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 80, -1));

        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/Save.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, 100, -1));

        btncetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/Print.png"))); // NOI18N
        btncetak.setText("Cetak");
        getContentPane().add(btncetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 100, -1));

        jLabel8.setText("Kode Sepatu");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel9.setText("Nama Sepatu");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel10.setText("Warna");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLabel11.setText("Harga");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));
        getContentPane().add(kode_sepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 80, -1));
        getContentPane().add(nama_sepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 150, -1));
        getContentPane().add(warna, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 150, -1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 150, -1));

        cari_sepatu.setText("Cari");
        cari_sepatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_sepatuActionPerformed(evt);
            }
        });
        getContentPane().add(cari_sepatu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 60, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/home-run.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Daftar Transaksi Penjualan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabel_transaksi);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 750, 170));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Total Bayar");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel7.setText("RP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 50, 50));

        jLabel14.setText("Bayar");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));

        jLabel15.setText("Kembalian");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        total.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 250, 50));

        bayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                bayarCaretUpdate(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 130, -1));
        jPanel1.add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 330, 230));

        jLabel3.setText("Jumlah Beli");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, 20));

        jLabel5.setText("Sub Total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, 20));

        jumlah_beli.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jumlah_beliCaretUpdate(evt);
            }
        });
        jumlah_beli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_beliActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah_beli, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 110, -1));

        sub_total.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                sub_totalCaretUpdate(evt);
            }
        });
        getContentPane().add(sub_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 110, -1));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 90, 40));

        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Transaksi Penjualan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 60));

        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, -1, -1));

        setSize(new java.awt.Dimension(904, 565));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        new MenuToko().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO `transpenjualan`( `tanggal`, `nama_sepatu`, `warna`, `harga`, `jumlah_beli`, `sub_total`, `total`, `bayar`, `kembalian`) VALUES (?,?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = con.prepareStatement(sql);           
            stat.setString(1, tgl);
            stat.setString(2, nama_sepatu.getText());
            stat.setString(3, warna.getText());
            stat.setString(4, harga.getText());
            stat.setString(5, jumlah_beli.getText());
            stat.setString(6, sub_total.getText());
            stat.setString(7, total.getText());
            stat.setString(8, bayar.getText());
            stat.setString(9, kembalian.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            kosongkan();
            no_trans.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan " +e);
        }
      

    }//GEN-LAST:event_btnsimpanActionPerformed

    private void cari_sepatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_sepatuActionPerformed
        // TODO add your handling code here:
        String sql = "select * from inputbrg where kode_sepatu ='"+kode_sepatu.getText()+"'";
        try {
            java.sql.Statement stat= con.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String kd = hasil.getString("nama_sepatu");
                String nm = hasil.getString("warna");
                String hrg = hasil.getString("harga");
                
                nama_sepatu.setText(kd);
                warna.setText(nm);
                harga.setText(hrg);
                
                nama_sepatu.setEnabled(false);
                warna.setEnabled(false);
                harga.setEnabled(false);
            }
        } catch (Exception e){
            
        }

    }//GEN-LAST:event_cari_sepatuActionPerformed

    private void bayarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_bayarCaretUpdate
        // TODO add your handling code here:
        double a;
        double b;
        double c;
        a = Double.parseDouble(bayar.getText());
        b = Double.parseDouble(total.getText());
        c = a - b;
        kembalian.setText(String.valueOf(c));
        kembalian.setEnabled(false);    

    }//GEN-LAST:event_bayarCaretUpdate

    private void jumlah_beliCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jumlah_beliCaretUpdate
        // TODO add your handling code here:
        double d,e,f;
        d = Double.parseDouble(harga.getText());
        e = Double.parseDouble(jumlah_beli.getText());
        f = d * e;
        sub_total.setText(String.format("%.2f", f));
        sub_total.setEnabled(false);
        total.setText(String.format("%.2f", f));

    }//GEN-LAST:event_jumlah_beliCaretUpdate

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        aktif();
        kosongkan();
        kode_sepatu.requestFocus();
        

    }//GEN-LAST:event_tambahActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:
        if(tanggal.getDate()!=null) {
            SimpleDateFormat format_tanggal = new SimpleDateFormat("yyyy-MM-dd");
            tgl= format_tanggal.format(tanggal.getDate());
    }
    }//GEN-LAST:event_tanggalPropertyChange

    private void jumlah_beliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_beliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_beliActionPerformed

    private void sub_totalCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_sub_totalCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_sub_totalCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Penjualan_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Penjualan_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Penjualan_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Penjualan_Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi_Penjualan_Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton cari_sepatu;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah_beli;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField kode_sepatu;
    private javax.swing.JTextField nama_sepatu;
    private javax.swing.JTextField no_trans;
    private javax.swing.JTextField sub_total;
    private javax.swing.JTable tabel_transaksi;
    private javax.swing.JButton tambah;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField total;
    private javax.swing.JTextField warna;
    // End of variables declaration//GEN-END:variables
}
