/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Penjualan;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wisnu
 */
public class Transaksi_Pembelian extends javax.swing.JFrame {
private Connection con = KoneksiDatabase.getkoneksi();
private DefaultTableModel tabmode;
private String tgl;
    /**
     * Creates new form Pembelian
     */
    public Transaksi_Pembelian() {
        initComponents();
        datatable();
    }

    private void datatable(){
        Object[] Baris = {"No Transaksi", "Tanggal","Kode Supplier","Nama Supplier","Kode Barang","Nama Barang","Harga Satuan","Qty","Total"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_transaksi.setModel(tabmode);
        String sql1 = "SELECT * FROM `transpembelian`";
        try{
            java.sql.Statement stat = con.createStatement();
            ResultSet hasil = stat.executeQuery(sql1);
            while(hasil.next()){
                String a = hasil.getString("notrans");
                String b = hasil.getString("tanggal");
                String c = hasil.getString("kodesupplier");
                String d = hasil.getString("namasupplier");
                String e = hasil.getString("kodebarang");
                String f = hasil.getString("namabarang");
                String g = hasil.getString("hargasatuan");
                String h = hasil.getString("qty");
                String i = hasil.getString("total");
                
                
                String[] data ={a,b,c,d,e,f,g,h,i};
                tabmode.addRow(data);
            }
            
            
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null,e);
    }
    }

private void aktif(){
        
        notrans.setEnabled(true);
        kodesupplier.setEnabled(true);
        namasupplier.setEnabled(true);
        kodebarang.setEnabled(true);
        namabarang.setEnabled(true);
        hargasatuan.setEnabled(true);
        notrans.requestFocus();
    }

private void kosongkan()
{
        tanggal.setDateFormatString("");
        notrans.setText("");
        kodesupplier.setText(""); 
        namasupplier.setText(""); 
        kodebarang.setText("");
        namabarang.setText("");
        hargasatuan.setText("");
        qty.setText("");
        total.setText("");
        notrans.requestFocus();
 } 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        notrans = new javax.swing.JTextField();
        kodesupplier = new javax.swing.JTextField();
        namasupplier = new javax.swing.JTextField();
        kodebarang = new javax.swing.JTextField();
        namabarang = new javax.swing.JTextField();
        hargasatuan = new javax.swing.JTextField();
        qty = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_transaksi = new javax.swing.JTable();
        cari_supplier = new javax.swing.JButton();
        save = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clea = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("TRANSAKSI PEMBELIAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Tanggal");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, -1, -1));

        jLabel3.setText("Kode Supplier");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        jLabel4.setText("Nama Supplier");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel5.setText("Kode Barang");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, -1));

        jLabel6.setText("Nama Barang");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 166, -1, -1));

        jLabel7.setText("No Trans");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 71, -1, -1));

        jLabel8.setText("Harga Satuan");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 165, -1, -1));

        jLabel9.setText("Qty");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 165, -1, -1));

        jLabel10.setText("Total");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));

        notrans.setEnabled(false);
        getContentPane().add(notrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 68, 97, -1));
        getContentPane().add(kodesupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 89, 110, -1));
        getContentPane().add(namasupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 127, 170, -1));
        getContentPane().add(kodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, -1));
        getContentPane().add(namabarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));
        getContentPane().add(hargasatuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 110, -1));
        getContentPane().add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 80, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 100, -1));

        tanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tanggalPropertyChange(evt);
            }
        });
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, -1));

        tabel_transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_transaksiMouseClicked(evt);
            }
        });
        tabel_transaksi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabel_transaksiKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_transaksi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 590, 120));

        cari_supplier.setText("cari");
        cari_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari_supplierActionPerformed(evt);
            }
        });
        getContentPane().add(cari_supplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        clea.setText("CLEAR");
        clea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleaActionPerformed(evt);
            }
        });
        getContentPane().add(clea, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(501, 220, 100, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Penjualan/gambar/home-run.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        setSize(new java.awt.Dimension(629, 573));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO `transpembelian`( `tanggal`,`kodesupplier`, `namasupplier`, `kodebarang`, `namabarang`, `hargasatuan`, `qty`, `total`) VALUES (?,?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = con.prepareStatement(sql);           
            stat.setString(1, tgl);
            stat.setString(2, kodesupplier.getText());
            stat.setString(3, namasupplier.getText());
            stat.setString(4, kodebarang.getText());
            stat.setString(5, namabarang.getText());
            stat.setString(6, hargasatuan.getText());
            stat.setString(7, qty.getText());
            stat.setString(8, total.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            kosongkan();
            notrans.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan " +e);
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cari_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari_supplierActionPerformed
        // TODO add your handling code here:
        String sql = "select * from supplier where Kode_Supplier ='"+kodesupplier.getText()+"'";
        try {
            java.sql.Statement stat= con.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                String nms = hasil.getString("Nama_Supplier");
                String kd = hasil.getString("kodebarang");
                String nmbrg = hasil.getString("namabarang");
                String hrgs = hasil.getString("hargasatuan");
                
                namasupplier.setText(nms);
                kodebarang.setText(kd);
                namabarang.setText(nmbrg);
                hargasatuan.setText(hrgs);
                
                namasupplier.setEnabled(false);
                kodebarang.setEnabled(false);
                namabarang.setEnabled(false);
                hargasatuan.setEnabled(false);
            }
        } catch (Exception e){
            
        }
    }//GEN-LAST:event_cari_supplierActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        double a;
        double b;
        double c;
        a = Double.parseDouble(hargasatuan.getText());
        b = Double.parseDouble(qty.getText());
        c = a * b;
        total.setText(String.valueOf(c));
        total.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tanggalPropertyChange
        // TODO add your handling code here:
        if(tanggal.getDate()!=null) {
            SimpleDateFormat format_tanggal = new SimpleDateFormat("yyyy-MM-dd");
            tgl= format_tanggal.format(tanggal.getDate());
        }
    }//GEN-LAST:event_tanggalPropertyChange

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try{
            String sql = "Update transpembelian set tanggal=?,kodesupplier=?,namasupplier=?,kodebarang=?,namabarang=?,hargasatuan=?,qty=?,total=? where notrans=?";
            PreparedStatement stat = con.prepareStatement (sql);
            stat.setString(1, tanggal.getDateFormatString());
            stat.setString(2, kodesupplier.getText());
            stat.setString(3, namasupplier.getText());
            stat.setString(4, kodebarang.getText());
            stat.setString(5, namabarang.getText());
            stat.setString(6, hargasatuan.getText());
            stat.setString(7, qty.getText());
            stat.setString(8, total.getText());
            stat.setString(9, notrans.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
            kosongkan();
            notrans.requestFocus();
            datatable();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah" +e);
        }
    }//GEN-LAST:event_editActionPerformed

    private void tabel_transaksiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabel_transaksiKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tabel_transaksiKeyPressed

    private void tabel_transaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_transaksiMouseClicked
        // TODO add your handling code here:
         int bar = tabel_transaksi.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();

        notrans.setText(a);
        tanggal.setDateFormatString(b);
        kodesupplier.setText(c);
        namasupplier.setText(d);
        kodebarang.setText(e);
        namabarang.setText(f);
        hargasatuan.setText(g);
        qty.setText(h);
        total.setText(i);
    }//GEN-LAST:event_tabel_transaksiMouseClicked

    private void cleaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleaActionPerformed
        // TODO add your handling code here:
        kosongkan();
    }//GEN-LAST:event_cleaActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql = "delete from transpembelian where notrans='"+notrans.getText()+"'";
            try{
                PreparedStatement stat = con.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil diHapus");
                kosongkan();
                notrans.requestFocus();
                datatable();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null,"Data Gagal di Hapus" +e);
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Pembelian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi_Pembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari_supplier;
    private javax.swing.JButton clea;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField hargasatuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField kodebarang;
    private javax.swing.JTextField kodesupplier;
    private javax.swing.JTextField namabarang;
    private javax.swing.JTextField namasupplier;
    private javax.swing.JTextField notrans;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel_transaksi;
    private com.toedter.calendar.JDateChooser tanggal;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
